const ts = require('typescript');
const fs = require('fs');
const vm = require('vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('src/services/bookingRules.ts', 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const sandbox = { exports: {}, require, Date }; vm.runInNewContext(compiled, sandbox);
const {servicePrice,validateSchedule,transition,isOpen}=sandbox.exports;
assert.equal(servicePrice({startingPriceMYR:48},'hatchback'),48);
assert.equal(servicePrice({startingPriceMYR:48},'suv'),62);
assert.equal(servicePrice({startingPriceMYR:48},'pickup'),72);
const now = new Date('2026-09-28T00:00:00Z');
assert.equal(validateSchedule('2026-09-29','10:00',now).toISOString(),'2026-09-29T02:00:00.000Z');
for(const [date,time] of [['Tomorrow','10:00'],['2026-09-27','10:00'],['2026-09-28','08:30'],['2026-09-29','07:00'],['2026-09-29','19:00'],['2026-11-01','10:00'],['2026-09-31','10:00'],['2026-09-29','10:99']]) assert.throws(()=>validateSchedule(date,time,now));
let b={id:'test',status:'confirmed',statusHistory:[]};
assert.throws(()=>transition(b,'completed'));
assert.equal(transition(b,'cancelled').status,'cancelled');
for(const status of ['assigned','on_the_way','arrived','washing','completed']) b=transition(b,status);
assert.equal(b.statusHistory.length,5);
assert.ok(b.completedAt);
assert.equal(transition(b,'completed'),b,'completion must be idempotent');
assert.equal(isOpen(b),false);
assert.throws(()=>transition(b,'washing'));
assert.throws(()=>transition({status:'on_the_way'},'cancelled'));
console.log('Booking rules: pricing, schedule boundaries, transitions, cancellation and idempotency passed.');
